wheel:
  mass: 1.0            # Wheel mass in Kilograms       
  radius: 0.053        # Wheel radius in meters 
  length: 0.033        # Wheel length in meters, considering it as a cylinder 
  mesh: 'wheel.dae'    # Name of the mesh files. Leave it empty ('') to have a red wheel. 
  x_offset: 0.128      # Offset distance on the x-axis in meters.
  y_offset: -0.052     # Offset distance on the y-axis in meters.
  z_offset: 0.045       # Offset distance on the z-axis in meters.